version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/booking-service-java"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/fake-services-nodejs"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/public-endpoint-nodejs"
    schedule:
      interval: "daily"

  # Although we should probably make sure we don't put those files in the root folder?
  # But I'll add this for now
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"