version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/booking-service-java"
    schedule:
      interval: "daily"
    groups:
      aws-sdk:
        patterns: [ "software.amazon.awssdk:*" ]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      aws-sdk:
        patterns: [ "@aws-sdk/*" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"