# Compose file to test Dockerfiles on local machine
# Should not be used to push to AWS

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ticketbooking-rabbitmq
    healthcheck:  # https://devops.stackexchange.com/questions/12092/docker-compose-healthcheck-for-rabbitmq
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  booking-service:
    build: ./booking-service-java
    container_name: ticketbooking-booking-service
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy

  fake-services:
    build: ./fake-services-nodejs
    container_name: ticketbooking-fake-services
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      # Since I don't think Docker copies the .env file into the image (yes I am leaking credentials but I'll change secrets when we get AWS Secrets set up)
      - ZEEBE_ADDRESS=83632c73-fe91-4d02-976d-e9ae69ba19a9.bru-2.zeebe.camunda.io:443
      - ZEEBE_CLIENT_ID=oN~X40IXOcApGsV0zAkrA6uRcOVLmWMC
      - ZEEBE_CLIENT_SECRET=g_YWlCGZ0_caNAiG210GMfS_B.p-yBjsWMj9ewiq_1aRR-9qKYWo~q_RUAfS_JYF
      - ZEEBE_AUTHORIZATION_SERVER_URL=https://login.cloud.camunda.io/oauth/token