# Compose file to test Dockerfiles on local machine
# Should not be used to push to AWS

services:
  booking-service:
    build: ./booking-service-java
    container_name: ticketbooking-booking-service
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy

  fake-services:
    build: ./fake-services-nodejs
    container_name: ticketbooking-fake-services
    depends_on:
      rabbitmq:
        condition: service_healthy