name: Cleanup PR Deployment
on:
  pull_request:
    types:
      - closed

jobs:
  destroy:
    runs-on: ubuntu-latest

    # Dependabot cannot create PR stacks so removing wouldn't work
    if: github.actor != 'dependabot[bot]'

    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          # ARN of the IAM role created for GitHub Actions OIDC
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-north-1

      - name: Create Dummy Asset for Synthesis
        run: |
          mkdir -p booking-service-java/target/
          touch booking-service-java/target/booking-service-lambda.jar

      - name: Destroy PR Stack
        run: |
          npm ci
          export STACK_ENV=PR-${{ github.event.number }}
          npx cdk destroy "TicketBookingStack-$STACK_ENV" --force
