name: Build & Deploy to AWS Lambda

on:
  push:
    branches: ["main", "ci_cd"]
    paths:
      - 'booking-service-java/src/main/java/io/berndrecker/ticketbooking/**'
      - '.github/workflows/deploy_booking-service.yml' # Also run if this config changes

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
  AWS_REGION: eu-north-1 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: ☕ Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🔧 Build project with Maven
      # Navigate to the subfolder where your code lives
        run: |
          cd booking-service-java
          mvn clean package -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}  # The role-to-assume should be the ARN of the IAM role you created for GitHub Actions OIDC

      - name: 🚀 Deploy to AWS Lambda using CLI (RetrievePayment)
        run: |
          aws lambda update-function-code \
            --function-name retrievePayment \
            --zip-file fileb://target/booking-service-lambda.jar
      
      - name: 🚀 Deploy to AWS Lambda using CLI (PaymentResponse)
        run: |
          aws lambda update-function-code \
            --function-name PaymentResponseHandler \
            --zip-file fileb://target/booking-service-lambda.jar
      
      - name: 🚀 Deploy to AWS Lambda using CLI (GenTicket)
        run: |
          aws lambda update-function-code \
            --function-name GenerateTicketHandler \
            --zip-file fileb://target/booking-service-lambda.jar