name: Deploy ticketGen to AWS Lambda

on:
  push:
    branches: [ "main", "ci_cd" ]
    paths:
      - 'fake-services-nodejs/src/ticketGen.ts'   # only run if the booking service changed
      - '.github/workflows/deploy_ticketGen.yml'  # Also run if this config changes

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_REGION: eu-north-1 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # Required to check out the repository
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Match your Lambda runtime version
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build and Package Functions
        run: |
          # Navigate to the subfolder where your code lives
          cd fake-services-nodejs
          
          # Install dependencies in that specific folder
          npm install
          
          # Create a dist folder
          mkdir -p dist
          
          # Bundle your specific file
          npx esbuild src/ticketGen.ts --bundle --platform=node --target=node20 --outfile=dist/index.js --external:@aws-sdk/*
          
          # Zip only the bundled file
          cd dist
          zip ticketGen.zip index.js
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}  # The role-to-assume should be the ARN of the IAM role you created for GitHub Actions OIDC
      
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ticketGen \
            --zip-file fileb://fake-services-nodejs/dist/ticketGen.zip