name: deploy_node-generic.yml
on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      entry_point:
        required: true
        type: string
      lambda_function_name:
        required: true
        type: string
      aws_region:
        required: false
        type: string

jobs:
  build:
    name: Build ${{ inputs.service_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './${{ inputs.working_directory }}/package-lock.json'

      - name: Build and Package
        run: |
          cd ${{ inputs.working_directory }}
          npm ci
          mkdir -p dist
          npx esbuild ${{ inputs.entry_point }} --bundle --platform=node --target=node20 --outfile=dist/index.js --external:@aws-sdk/*
          zip -j ${{ inputs.service_name }}.zip dist/index.js

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.service_name }}-artifact
          path: ${{ inputs.working_directory }}/${{ inputs.service_name }}.zip
          retention-days: 1

  deploy:
    name: Deploy ${{ inputs.service_name }}
    needs: build
    # We might at some point want to start disallowing pr deploy
    #if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # Required to check out the repository
    steps:
      - name: Download Package
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.service_name }}-artifact

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}  # ARN of IAM rile for GitHub Actions OIDC
          aws-region: ${{ inputs.aws_region }}

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ inputs.lambda_function_name }} \
            --zip-file fileb://${{ inputs.service_name }}.zip
