name: Deploy payment to AWS Lambda

on:
  workflow_dispatch:
  push:
    branches: [ "main", "ci_cd" ]
    paths:
      - 'fake-services-nodejs/src/payment.ts'   # only run if the booking service changed
      - 'fake-services-nodejs/package.json'
      - 'fake-services-nodejs/tsconfig.json'
      - '.github/workflows/deploy_payment.yml'  # Also run if this config changes
      - '.github/workflows/deploy_node-generic.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'fake-services-nodejs/src/payment.ts'   # only run if the booking service changed
      - 'fake-services-nodejs/package.json'
      - 'fake-services-nodejs/tsconfig.json'
      - '.github/workflows/deploy_payment.yml'  # Also run if this config changes
      - '.github/workflows/deploy_node-generic.yml'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  call-deploy:
    uses: '.github/workflows/deploy_node-generic.yml'
    with:
      aws_region: ${{ env.AWS_REGION }}
      entry_point: 'src/payment.ts'
      lambda_function_name: 'paymentService'
      service_name: 'payment'
      working_directory: 'fake-services-nodejs'
    secrets: inherit
