name: Deploy public endpoint to AWS Lambda

on:
  workflow_dispatch:
  push:
    branches: [ "main", "ci_cd" ]
    paths:
      - 'public-endpoint-nodejs/**'
      - '.github/workflows/deploy_public_endpoint.yml'  # Also run if this config changes
      - '.github/workflows/deploy_node-generic.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'public-endpoint-nodejs/**'
      - '.github/workflows/deploy_public_endpoint.yml'  # Also run if this config changes
      - '.github/workflows/deploy_node-generic.yml'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  call-deploy:
    uses: '.github/workflows/deploy_node-generic.yml'
    with:
      aws_region: ${{ env.AWS_REGION }}
      entry_point: 'src/index.ts'
      lambda_function_name: 'publicEndpoint'
      service_name: 'publicEndpoint'
      working_directory: 'public-endpoint-nodejs'
    secrets: inherit
