name: Java Build & Test
on:
  workflow_call:

env:
  JAVA_VERSION: 25

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Spotless Format Check
        working-directory: ./booking-service-java
        run: mvn spotless:check

      - name: Build
        id: build
        if: ! cancelled()
        working-directory: ./booking-service-java
        # Runs tests, compilation, integrated plugins
        run: mvn -B -ntp verify

      - name: SpotBugs Check
        if: ! cancelled() && steps.build.outcome == 'success'
        working-directory: ./booking-service-java
        run: mvn -B -ntp spotbugs:check

      - name: Upload Artifact
        if: (! cancelled()) && success()
        uses: actions/upload-artifact@v7
        with:
          name: booking-service-jar
          path: booking-service-java/target/booking-service-lambda.jar
