name: Java Build & Test
on:
  workflow_call:

env:
  JAVA_VERSION: 25

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Spotless Format Check
        id: spotless
        continue-on-error: true
        working-directory: ./booking-service-java
        run: mvn spotless:check

      - name: SpotBugs Check
        id: spotbugs
        continue-on-error: true
        working-directory: ./booking-service-java
        run: mvn compile spotbugs:check

      - name: Build
        id: build
        continue-on-error: true
        working-directory: ./booking-service-java
        # Runs tests, compilation, integrated plugins
        run: mvn clean verify

      - name: Stop on Failure
        if: steps.spotless.outcome == 'failure' ||
          steps.spotbugs.outcome == 'failure' ||
          steps.build.outcome == 'failure'
        run: |
          echo "One or multiple steps failed, exiting."
          exit 1

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: booking-service-jar
          path: booking-service-java/target/booking-service-lambda.jar
