name: Java Build & Test
on:
  workflow_call:

env:
  JAVA_VERSION: 25

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Test
        working-directory: ./booking-service-java
        run: mvn test  # Allows for tests when we make them

      - name: Build
        working-directory: ./booking-service-java
        run: mvn clean package -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: booking-service-jar
          path: booking-service-java/target/booking-service-lambda.jar
