name: Node Build & Test
on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      artifact_name:
        required: true
        type: string


env:
  NODE_VERSION: 24


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'npm'
          cache-dependency-path: './${{ inputs.working_directory }}/package-lock.json'

      - name: Install & Test
        run: |
          npm ci
          npm test --workspace=${{ inputs.working_directory }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.working_directory }}
          retention-days: 1
