name: Node Build & Test
on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      artifact_name:
        required: true
        type: string


env:
  NODE_VERSION: 24


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Security Audit
        id: sec
        continue-on-error: true
        run: npm audit --audit-level=high

      - name: Check Formatting (Prettier)
        id: form
        continue-on-error: true
        run: npx prettier --check .

      - name: Lint (ESLint)
        id: lint
        continue-on-error: true
        run: npx eslint .

      - name: Type Check
        id: type
        continue-on-error: true
        run: npm run type-check

      - name: Validate ASL
        id: asl
        continue-on-error: true
        run: npm run asl-validate

      - name: Test
        id: test
        continue-on-error: true
        run: npm test --workspace=${{ inputs.working_directory }}

      - name: Stop on Failure
        if: steps.sec.outcome == 'failure' ||
            steps.form.outcome == 'failure' ||
            steps.lint.outcome == 'failure' ||
            steps.type.outcome == 'failure' ||
            steps.asl.outcome == 'failure' ||
            steps.test.outcome == 'failure'
        run: |
          echo "One or multiple steps failed, exiting."
          exit 1

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.working_directory }}
          retention-days: 1
