name: Pipeline
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      run_load_tests:
        description: 'Set to "true" at manual workflow dispatch to run the load test suite'
        required: false
        default: false
        type: boolean

# Stop old pipeline if new one starts
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 24

jobs:
  build-java:
    name: Java
    uses: './.github/workflows/java-build-test.yml'

  build-node:
    name: NodeJS ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - dir: 'public-endpoint-nodejs'
            name: 'Public Endpoint'
            asset-name: 'public-endpoint-node-assets'
          - dir: 'fake-services-nodejs'
            name: 'Fake Services'
            asset-name: 'fake-services-node-assets'
    uses: './.github/workflows/node-build-test.yml'
    with:
      working_directory: ${{ matrix.dir }}
      readable_name: ${{ matrix.name }}
      artifact_name: ${{ matrix.asset-name }}

  test-infra:
    name: Test Infrastructure
    needs: [build-java]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Download Java Artifact
        uses: actions/download-artifact@v8
        with:
          name: booking-service-jar
          path: booking-service-java/target/

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Validate ASL
        run: npm run asl-validate

      - name: CDK Synth
        run: npx cdk synth

  deploy:
    name: Deploy to AWS
    needs: [build-java, build-node, test-infra]
    runs-on: ubuntu-latest

    outputs:
      api_url: ${{ steps.extract-url.outputs.api_url }}

    # Disallows dependabot creating PR stacks, but does update production on merge
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]')

    permissions:
      id-token: write
      contents: read

    env:
      # PR number for PRs, 'Prod' for main branch pushes
      STACK_ENV: ${{ github.event_name == 'pull_request' && format('PR-{0}', github.event.number) || 'Prod' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Download Java Artifact
        uses: actions/download-artifact@v8
        with:
          name: booking-service-jar
          path: booking-service-java/target/

      - name: Download Public Endpoint Assets
        uses: actions/download-artifact@v8
        with:
          name: public-endpoint-node-assets
          path: public-endpoint-nodejs/

      - name: Download Fake Services Assets
        uses: actions/download-artifact@v8
        with:
          name: fake-services-node-assets
          path: fake-services-nodejs/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          # ARN of the IAM role created for GitHub Actions OIDC
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-north-1

      - name: CDK Deploy
        run: |
          npm ci
          export STACK_ENV=${{ env.STACK_ENV }}
          npx cdk deploy "TicketBookingStack-$STACK_ENV" --require-approval never --outputs-file cdk-outputs.json

      - name: Extract API URL
        id: extract-url
        run: |
          # Retrieve URL from JSON file
          STACK_NAME="TicketBookingStack-${{ env.STACK_ENV }}"
          API_URL=$(jq -r ".[\"$STACK_NAME\"].ApiGatewayUrl" cdk-outputs.json)

          # Stop if URL not found, tests mysteriously fail otherwise
          if [ -z "$API_URL" ]; then
            echo "Error: Could not find ApiGatewayUrl for stack $STACK_NAME in cdk-outputs.json"
            exit 1
          fi

          echo "api_url=$API_URL" >> $GITHUB_OUTPUT

  e2e-test:
    name: End-to-End Tests
    needs: [deploy]
    runs-on: ubuntu-latest

    # Only if deploy was successful
    if: success()

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: Run E2E Tests
        env:
          API_URL: ${{ needs.deploy.outputs.api_url }}
        run: |
          npm install tsx
          npx tsx --test tests/e2e/booking.test.ts

  load-test:
    needs: e2e-test
    runs-on: ubuntu-latest

    # Only run manually
    if: |
      github.event_name == 'workflow_dispatch' && 
      inputs.run_load_tests == true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run Load Suite (Lowest to Highest)
        env:
          API_URL: ${{ needs.deploy.outputs.api_url }}
          ARTILLERY_DISABLE_TELEMETRY: 'false'
          ARTILLERY_API_KEY: ${{ secrets.ARTILLERY_API_KEY }}
        run: |
          # In order
          TEST_FILES=(
            "extremely_low_load"
            "low_load"
            "low_medium_load"
            "medium_load"
            "full_load"
          )

          for STRATEGY in "${TEST_FILES[@]}"; do
            echo "Starting Load Strategy: $STRATEGY"

            npx artillery run \
              --record \
              --key "$ARTILLERY_API_KEY" \
              --env-name "$STRATEGY" \
              "tests/load_tests/$STRATEGY.yaml"

            echo "Completed $STRATEGY"
            echo "-------------------------------------------"
          done
