name: Pipeline
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      run_load_tests:
        description: 'Run Load Test Suite'
        required: false
        default: false
        type: boolean

# Stop old pipeline if new one starts
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 24

jobs:
  build-node:
    name: NodeJS ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - dir: 'public-endpoint-nodejs'
            name: 'Public Endpoint'
            asset-name: 'public-endpoint-node-assets'
          - dir: 'fake-services-nodejs'
            name: 'Fake Services'
            asset-name: 'fake-services-node-assets'
          - dir: 'booking-service'
            name: 'Internal Booking Service'
            asset-name: 'booking-service-assets'
    uses: './.github/workflows/node-build-test.yml'
    with:
      working_directory: ${{ matrix.dir }}
      readable_name: ${{ matrix.name }}
      artifact_name: ${{ matrix.asset-name }}

  test-infra:
    name: Test Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Validate ASL
        run: npm run asl-validate

      - name: CDK Synth
        run: npx cdk synth

  deploy:
    name: Deploy to AWS
    needs: [build-node, test-infra]
    runs-on: ubuntu-latest

    outputs:
      api_url: ${{ steps.extract-url-http.outputs.api_url }}
      ws_url: ${{ steps.extract-url-ws.outputs.ws_url }}

    # Disallows dependabot creating PR stacks, but does update production on merge
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]') ||
      github.event_name == 'workflow_dispatch'

    permissions:
      id-token: write
      contents: read

    env:
      # PR number for PRs, 'Prod' for main branch pushes
      STACK_ENV: ${{ github.event_name == 'pull_request' && format('PR-{0}', github.event.number) || 'Prod' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Download Booking Service Assets
        uses: actions/download-artifact@v8
        with:
          name: booking-service-assets
          path: booking-service/

      - name: Download Public Endpoint Assets
        uses: actions/download-artifact@v8
        with:
          name: public-endpoint-node-assets
          path: public-endpoint-nodejs/

      - name: Download Fake Services Assets
        uses: actions/download-artifact@v8
        with:
          name: fake-services-node-assets
          path: fake-services-nodejs/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          # ARN of the IAM role created for GitHub Actions OIDC
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-north-1

      - name: CDK Deploy
        run: |
          npm ci
          export STACK_ENV=${{ env.STACK_ENV }}
          npx cdk deploy "TicketBookingStack-$STACK_ENV" --require-approval never --outputs-file cdk-outputs.json

      - name: Extract API URL
        id: extract-url-http
        run: |
          # Retrieve HTTP URL from JSON file
          STACK_NAME="TicketBookingStack-${{ env.STACK_ENV }}"
          API_URL=$(jq -r ".[\"$STACK_NAME\"].HttpApiUrl" cdk-outputs.json)

          # Stop if URL not found, tests mysteriously fail otherwise
          if [ -z "$API_URL" ]; then
            echo "Error: Could not find HttpApiUrl for stack $STACK_NAME in cdk-outputs.json"
            exit 1
          fi

          echo "api_url=$API_URL" >> $GITHUB_OUTPUT

      - name: Extract WS URL
        id: extract-url-ws
        run: |
          # Retrieve WS URL from JSON file
          STACK_NAME="TicketBookingStack-${{ env.STACK_ENV }}"
          API_URL=$(jq -r ".[\"$STACK_NAME\"].WebSocketUrl" cdk-outputs.json)

          # Stop if URL not found, tests mysteriously fail otherwise
          if [ -z "$API_URL" ]; then
            echo "Error: Could not find WebSocketUrl for stack $STACK_NAME in cdk-outputs.json"
            exit 1
          fi

          echo "ws_url=$API_URL" >> $GITHUB_OUTPUT

  e2e-test:
    name: End-to-End Tests
    needs: [deploy]
    runs-on: ubuntu-latest

    # Only if deploy was successful
    if: success()

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run E2E Tests
        env:
          API_URL: ${{ needs.deploy.outputs.api_url }}
          WSS_URL: ${{ needs.deploy.outputs.ws_url }}
        run: |
          npx tsx --test tests/e2e/booking.test.ts

  load-test:
    name: Load Test ${{ matrix.name }}
    needs: [deploy, e2e-test]
    runs-on: ubuntu-latest

    # Only run manually
    if: |
      github.event_name == 'workflow_dispatch' && 
      inputs.run_load_tests == true

    strategy:
      max-parallel: 1
      fail-fast: true # Set to true if you want to stop the whole suite if one level fails
      matrix:
        include:
          - name: Medium
            load_level: medium_load
          - name: Full
            load_level: full_load

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run Load Suite ${{ matrix.name }}
        env:
          WSS_URL: ${{ needs.deploy.outputs.ws_url }}
        run: |
          mkdir -p reports
          npx artillery run \
            -e ${{ matrix.load_level }} \
            --output "reports/${{ matrix.load_level }}.json" \
            tests/load_tests/load_test.yaml

      - name: Upload Load Test Reports
        uses: actions/upload-artifact@v7
        if: always() # Also if a test fails
        with:
          name: artillery-report-${{ matrix.load_level }}
          path: reports/
          retention-days: 7
