name: Security
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    # Weekly in case vulnerabilities are found in already existing packages
    - cron: '0 0 * * 0'

env:
  JAVA_VERSION: 25

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          # Hopefully prevent Gitleaks crash on first commit of PR?
          fetch-depth: 0

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  codeql:
    name: CodeQL Analysis / ${{ matrix.display_name }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: 'java'
            display_name: 'Java'
          - language: 'javascript'
            display_name: 'NodeJS'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Initialise CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - if: matrix.language == 'java'
        name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - if: matrix.language == 'java'
        name: Build Java
        run: mvn -B -ntp -f booking-service-java/pom.xml clean install -DskipTests

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
