name: Security
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    # Weekly in case vulnerabilities are found in already existing packages
    - cron: '0 0 * * 0'

env:
  JAVA_VERSION: 25

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          # Hopefully prevent Gitleaks crash on first commit of PR?
          fetch-depth: 0

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Initialise CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: 'javascript'
          config: |
            paths-ignore:
              - '**/tests/**'
              - '**/*.test.ts'
